Profile stores
HackRU/frontend-core pull request #14
Opened 2021-03-10 22:52 UTC by zain08816

Resolves #13

Add the Profile object and new defaults into store.

#### WIP
- fix rollup config to include store?
- pass Profile as default store

2021-03-25 18:57 UTC, zain08816 commented
Currently, this branch temporarily moves Defaults to the Profile file. Rollup was misbehaving and recognizing the Defaults import into Profile a weird way in the cjs dist/index.js. Defaults *can* be left in Profile as many things that use Defaults also use Profile, but they should probably be separate stores in the end.

2021-03-26 18:10 UTC, zain08816 commented
> Currently, this branch temporarily moves Defaults to the Profile file. Rollup was misbehaving and recognizing the Defaults import into Profile a weird way in the cjs dist/index.js. Defaults _can_ be left in Profile as many things that use Defaults also use Profile, but they should probably be separate stores in the end.

I was sleeping and I realized what was wrong and how simple it was.

2021-04-12 02:07 UTC, shivanmodha commented on package/src/CoreProvider.js
> +    _store = Store;
We want the user to be able to override the defaults.

2021-04-12 02:11 UTC, shivanmodha requested changes
Good job! Let's just fix the final store override features, and we good

2021-04-22 01:01 UTC, shivanmodha approved these changes

2021-04-22 01:01 UTC, merged